### ISSUE TITLE
Can't connect to Navidrome

### ISSUE THREAD

**Issue by bbsixzz** [halpz/HalpoPlayer#1] opened 2023-08-29 06:35 UTC
The info is correct, works in my other subsonic app Amperfy.

**Comment by bbsixzz** [comment] 2023-08-30 22:25
![image](https://github.com/halpz/HalpoPlayer/assets/47334163/35c78ad7-9add-45e9-a770-af80ea4fc13e)
![image](https://github.com/halpz/HalpoPlayer/assets/47334163/6a0513af-3257-4466-90f6-1b53b8b67075)

If I enter the port number twice as shown it seems to connect but everything is empty.

**Comment by halpz** [comment] 2023-08-31 12:38
you don't need to include the port in the address field since it is entered in the port field

**Comment by bbsixzz** [comment] 2023-08-31 18:42
If I only enter http://10.0.1.2 it doesn't connect and throws me back to the login screen.

**Comment by bbsixzz** [comment] 2023-08-31 19:07
Here's a video of the problem and a switch to Amperfy showing it working fine.

https://github.com/halpz/HalpoPlayer/assets/47334163/3f0d508b-0b4d-4b30-b270-c370b06261de

**Comment by halpz** [comment] 2023-09-01 08:17
@bbsixzz I'm currently trying to solve this - would you like to test the next build through TestFlight? I'm not able to reproduce this bug myself - DM me your Apple ID if so!

**Comment by bbsixzz** [comment] 2023-09-01 14:56
No sweat, I will gladly help I sent you a DM on reddit.

**Comment by halpz** [comment] 2023-09-07 09:57
@Normanras no problem - send me your details on reddit! 
https://www.reddit.com/user/halpz/

**Comment by halpz** [comment] 2023-09-07 10:51
can you try the latest build on GitHub (it's the same as TestFlight)

**Comment by Normanras** [comment] 2023-09-07 14:53
> @Normanras no problem - send me your details on reddit! https://www.reddit.com/user/halpz/

Done! Should be in your messages, @halpz. Thanks!

**Comment by bbsixzz** [comment] 2023-09-07 20:12
Same problem with latest testflight.

**Comment by halpz** [comment] 2023-09-08 13:48
@bbsixzz hmm strange - would it be possible for me to test it with your server? could you create a temporary user for me to test?

**Comment by halpz** [comment] 2023-09-08 13:55
@bbsixzz when you are connecting to your LAN, do you use a password?

**Comment by bbsixzz** [comment] 2023-09-08 14:13
Yes I use a password, screenshots and videos hide it in iOS.

I'm afraid I can't enable WAN access to my network.

**Comment by halpz** [comment] 2023-09-08 14:26
ok can you try this build - I have enabled alert views whenever there is an error and tell me what you see?
http://paulhalpin.co.uk:8282/api/public/dl/X99q4ETA/downloads/HalpoPlayer.ipa

**Comment by halpz** [comment] 2023-09-08 14:26
unless you cannot sign it yourself?

**Comment by bbsixzz** [comment] 2023-09-08 14:35
I'll have a look at the build later, what you see in the screen capture is what I see, I don't know if I'm signing in because the app gives no feedback.

You can input www.gooogle.com as address with no password and it will give the same result.

It never says wrong address/password.

Signing in works fine in the browser or using the app Amperfy.

**Comment by halpz** [comment] 2023-09-08 14:45
@Normanras feel free try this too if you're having the same problem

**Comment by bbsixzz** [comment] 2023-09-08 19:47
I won't be able to test your build for a while but you can do this instead:

Connect to https://demo.navidrome.org (works in [Amperfy](https://github.com/BLeeEZ/amperfy) and [Supersonic](https://github.com/dweymouth/supersonic)).

Use login `demo` and password `demo`.

**Comment by halpz** [comment] 2023-10-10 14:37
I have created a fix for this issue that should be live on the App Store in the next day or so (or build from source)

**Closed by halpz** 2023-10-10 14:37 UTC

**Comment by bbsixzz** [comment] 2023-10-21 02:08
Just FYI Testflight version is still stuck on 1.0.3

**Comment by bbsixzz** [comment] 2023-10-21 17:00
1.0.7 works now Testflight just updated!

**Comment by ema07cqc** [comment] 2023-10-21 17:03
hello @bbsixzz is there a testflight link? Thanks!

**Comment by bbsixzz** [comment] 2023-10-21 17:06
Send a message to the dev on reddit the info is at the top @ema07cqc
